export const PAGINATION = {
	DEFAULT_PAGE: 1,
	DEFAULT_LIMIT: 20,
	MAX_LIMIT: 100,
	PUBLIC_COLLECTION_LIMIT: 50,
	PUBLIC_COLLECTION_MAX: 200,
	GEOCODE_DEFAULT: 5,
	GEOCODE_MIN: 1,
	GEOCODE_MAX: 10,
} as const;
