export const GAME_CONSTRAINTS = {
	COMPLEXITY_MIN: 1,
	COMPLEXITY_MAX: 5,
	MAX_PLAYERS_LIMIT: 100,
	MIN_PLAYERS_EVENT: 2,
	COVER_IMAGE_MAX_LENGTH: 50,
} as const;

export const PROFILE_CONSTRAINTS = {
	FIRST_NAME_MIN: 1,
	FIRST_NAME_MAX: 50,
	LAST_NAME_MIN: 1,
	LAST_NAME_MAX: 50,
	USERNAME_MIN: 3,
	USERNAME_MAX: 30,
	PHONE_MIN_DIGITS: 9,
	PHONE_MAX_DIGITS: 15,
	POSTAL_CODE_MIN_DIGITS: 4,
	POSTAL_CODE_MAX_DIGITS: 10,
	LOCATION_MAX: 100,
	BIO_MAX: 300,
} as const;

export const ORGANISER_CONSTRAINTS = {
	ORG_NAME_MIN: 2,
	ADDRESS_MIN: 5,
} as const;

export const GEO = {
	LAT_MIN: -90,
	LAT_MAX: 90,
	LON_MIN: -180,
	LON_MAX: 180,
} as const;

export const LOCATION_CONSTRAINTS = {
	CAPACITY_MIN: 1,
} as const;

export const SEARCH_CONSTRAINTS = {
	QUERY_MIN: 1,
	QUERY_MAX: 200,
} as const;
